version: "3"

services:

  shopware:
    build: .
    image: shadowcodes/synshopware:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "6379:6379"
      - "81:81"
      - "1025:1025"
      - "1080:1080"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - PHP_VERSION=8.2
volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false