#!bin/bash

### BEGIN INIT INFO
# Provides:          nginx-exporter
# Required-Start:    $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start nginx service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=nginx-exporter
DESC="Nginx-exporter"
NGINX_EXPORTER_HOME=/etc/nginx-exporter
PID_FILE=/var/run/$NAME.pid
DAEMON=$NGINX_EXPORTER_HOME/nginx-prometheus-exporter


. /lib/init/vars.sh
. /lib/lsb/init-functions

STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"

if [ ! -x $DAEMON ]; then
  echo "Program not installed or not executable"
  exit 5
fi

start_nginx_exporter() {

	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
		$DAEMON_OPTS 2>/dev/null \
		|| return 2
}

stop_nginx_exporter() {
	start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
	RETVAL="$?"
	sleep 1
	return "$RETVAL"
}

reload_nginx_exporter() {
	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
	return 0
}
 case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    start_nginx_exporter
    case "$?" in
      0|1) log_end_msg 0 ;;
      2)   log_end_msg 1 ;;
    esac
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    stop_nginx_exporter
    case "$?" in
      0|1) log_end_msg 0 ;;
      2)   log_end_msg 1 ;;
    esac
    ;;
  restart)
    log_daemon_msg "Restarting $DESC" "$NAME"

    if ! test_config; then
      log_end_msg 1
      exit $?
    fi

    stop_nginx_exporter
    case "$?" in
      0|1)
        start_nginx_exporter
        case "$?" in
          0) log_end_msg 0 ;;
          1) log_end_msg 1 ;;
          *) log_end_msg 1 ;;
        esac
        ;;
      *)
        log_end_msg 1
        ;;
    esac
    ;;
  reload|force-reload)
    log_daemon_msg "Reloading $DESC configuration" "$NAME"

    if ! test_config; then
      log_end_msg 1
      exit $?
    fi

    reload_nginx_exporter
    log_end_msg $?
    ;;
  status)
    status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
esac